name: soleh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.1
  dependency_validator: ^5.0.3
  device_preview: ^1.3.1
  flutter_bloc: ^9.1.1
  fluentui_system_icons: ^1.1.229
  flutter_dotenv: ^6.0.0
  flutter_islamic_icons: ^1.0.2
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  flutter_map_marker_cluster: ^8.2.2
  flutter_map_marker_popup: ^8.1.0
  flutter_neumorphic_plus: ^3.3.0
  flutter_speed_dial: ^7.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  html: ^0.15.6
  http: ^1.2.1
  latlong2: ^0.9.0
  location: ^8.0.1
  material_symbols_icons: ^4.2780.0
  simple_icons: ^14.6.1
  supabase_flutter: ^2.10.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Soleh.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Soleh.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/Soleh.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Soleh.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
